### ISSUE TITLE
OAuth process broken due to Yammer changes

### ISSUE THREAD

**Issue by oscarrenalias** [jaredhanson/passport-yammer#3]
Seems that Yammer recently changed their OAuth 2.0 authentication process to require the OAuth 2.0 token in an Authorization: Bearer token rather than as a query string as it used to be: http://developer.yammer.com/authentication/ (under "Making API requests"). I think it was announced at some point in Yammer's Developer Network but can't find it anymore.

Nevertheless, this means that the current implementation of passport-yammer is broken and it no longer works. It's a tiny fix that I already have in place :), so a pull request is coming in shortly.

**Comment by mauricionr** [comment]
![image](https://cloud.githubusercontent.com/assets/2263551/7781708/cf55a876-00ca-11e5-92c2-e8cca5b10cf2.png)


I'm getting 401 and i'm using passport-yammer2, @oscarrenalias could you help me?

**Comment by oscarrenalias** [comment]
@mauricionr, it doesn't look like my pull request was merged, and it looks like this module has not been updated for over 2 years by now. 

You could try using my branch and see if that helps. And it would be useful to know the exact error that you're getting.

**Comment by mauricionr** [comment]
@oscarrenalias, I think i was getting unauthorized because i was'nt a verified admin.
now it works!

**Comment by fiznool** [comment]
@oscarrenalias there are other passport modules that have suffered the same fate as this one, i.e. they are outdated with fixes pending.

Perhaps you could publish a new module, `passport-yammer-oauth2` which we could all then point at, rather than relying on your branch?

Either that, or you could start an npm dispute to try and take ownership of the module name: https://docs.npmjs.com/misc/disputes

**Comment by jfstephe** [comment]
@oscarrenalias @jaredhanson - can you offer some guidance on the state of this module and the likelihood of the issues being resolved and PRs being merged?

**Comment by oscarrenalias** [comment]
Unfortunately, I am no longer using this module and have no plans to continue the development. Maybe someone would like to fork my branch and continue the development there?
